In [2]:
import pandas as pd
import numpy as np
import os
import gensim
import nltk

In [3]:
#Download Resources from nltk(Natural Language ToolKit) Package used to Text Preprocessing
# (TokeniZation,word level Tokenization,Sentense level Tokenization ....)
nltk.download("all")

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to
[nltk_data]    |     C:\Users\anilp\AppData\Roaming\nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to
[nltk_data]    |     C:\Users\anilp\AppData\Roaming\nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\anilp\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     C:\Users\anilp\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     C:\Users\anilp\AppData\Roaming\nltk_data...
[

True

In [4]:
from nltk import sent_tokenize #Splits text into sentences and no modification in oiriginal Text
from gensim.utils import simple_preprocess #Tokenizes text into words and lowercases text ,it removes punctuation

In [5]:
for file in os.listdir('C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Assignment\Custom_Word2Vec_Training\Data'):
    print(file)

story3.txt
story4.txt


In [6]:
#Now Load and Read data from both Data Files Together and perform tokenization
#Step 1: Load Both files into Memory
#Step 2: Convert paragraph into sentense using sent_tokenize from nltk library
#step 3: Convert each sentense into words(Tokens) using simple_process from gensim.utils library

folder_path = r"C:\Mine\AI\Full Stack Gen AI  BootCamp (KrishNaik)\Practicals\Assignment\Custom_Word2Vec_Training\Data"
story = []
for filename in os.listdir(folder_path):
  file_path=os.path.join(folder_path,filename)
  with open(file_path,encoding='unicode_escape') as f:
    corpus=f.read()
  raw_sent=sent_tokenize(corpus)
  for sent in raw_sent:
    story.append(simple_preprocess(sent))
    
    

In [6]:
story

[['once',
  'upon',
  'time',
  'there',
  'was',
  'young',
  'boy',
  'named',
  'arjun',
  'who',
  'lived',
  'in',
  'small',
  'town',
  'surrounded',
  'by',
  'hills',
  'and',
  'rivers'],
 ['he',
  'was',
  'very',
  'curious',
  'about',
  'how',
  'things',
  'worked',
  'and',
  'always',
  'asked',
  'questions'],
 ['his',
  'parents',
  'often',
  'smiled',
  'at',
  'his',
  'curiosity',
  'and',
  'encouraged',
  'him',
  'to',
  'learn',
  'more'],
 ['every',
  'day',
  'after',
  'school',
  'arjun',
  'would',
  'sit',
  'with',
  'his',
  'books',
  'and',
  'explore',
  'different',
  'topics'],
 ['he',
  'was',
  'especially',
  'fascinated',
  'by',
  'science',
  'and',
  'technology'],
 ['he',
  'wanted',
  'to',
  'understand',
  'how',
  'machines',
  'think',
  'and',
  'whether',
  'they',
  'could',
  'become',
  'as',
  'intelligent',
  'as',
  'humans'],
 ['one',
  'day',
  'while',
  'browsing',
  'through',
  'an',
  'old',
  'computer',
  'at',
  'sc

In [7]:
#Check length of sentense 
len(story)

95

In [8]:
#check tokens from each sentense now
story[80]

['university', 'life', 'was', 'both', 'exciting', 'and', 'overwhelming']

In [15]:
#Loads Model into memory now
#All Parameters those are mentioned inside model are Hyperparameters
#window : This parameter is hyper parameters which 
#min_count : Words Considered only whne more that mentioned number (ex: min_count=5)
        # sunny->100
        # Divyansh->6
        # Rahul->3
                    #Rahul is not considered since its frequency of occurance is 3
#Vector_Size: model will be trained only with that dimension (i,e., Features)

# Word2Vec(..., sg=0)  # Here sg=0 defines word2vec selected for training is CBOW #by default if mentioned nothing inside model parameter
# Word2Vec(..., sg=1)  # Here sg=0 defines word2vec selected for training is Skip-gram
custom_model=gensim.models.Word2Vec(
   window=10,
   min_count=5,# min_count=5 is default value
   vector_size=150
   #sg=1
)

In [18]:
#Build Vocabulary
custom_model.build_vocab(story)

In [20]:
"crop" in custom_model.wv

True

In [21]:
vocab_words=list(custom_model.wv.index_to_key)
print(vocab_words)

['and', 'he', 'his', 'to', 'the', 'arjun', 'him', 'was', 'that', 'in', 'of', 'with', 'small', 'by', 'at', 'but', 'learning', 'started', 'on', 'for', 'not', 'had', 'could', 'about', 'more', 'day', 'data', 'time', 'crop', 'this', 'farmers', 'world', 'were', 'as', 'projects', 'system', 'real', 'weather', 'built', 'always', 'technology', 'across', 'many', 'problems', 'work', 'from', 'people']


In [22]:
#Check Word Frequency
print(custom_model.wv.get_vecattr("crop","count"))

6


In [23]:
#Check all words frequency in Vocabulary
for word in vocab_words:
    print(f"{word} : {custom_model.wv.get_vecattr(word,'count')}")

and : 61
he : 56
his : 45
to : 34
the : 33
arjun : 23
him : 21
was : 20
that : 20
in : 18
of : 18
with : 12
small : 10
by : 9
at : 9
but : 9
learning : 8
started : 8
on : 7
for : 7
not : 7
had : 7
could : 6
about : 6
more : 6
day : 6
data : 6
time : 6
crop : 6
this : 6
farmers : 6
world : 6
were : 6
as : 5
projects : 5
system : 5
real : 5
weather : 5
built : 5
always : 5
technology : 5
across : 5
many : 5
problems : 5
work : 5
from : 5
people : 5


In [26]:
#Full Vocabulary Summary
print(f"Vocabulary Size  : {len(custom_model.wv)}")
print(f"Vector Dimension : {custom_model.vector_size}")
print(f"Most frequent    : {custom_model.wv.index_to_key[0]}")
print(f"Least frequent   : {custom_model.wv.index_to_key[-1]}")

Vocabulary Size  : 47
Vector Dimension : 150
Most frequent    : and
Least frequent   : people


In [27]:
#Total Number of Sentences inside data file
custom_model.corpus_count

95

In [28]:
#Lets Train Model now
#total_examples : This is mandate otherwise model wont be trained
#epocs: No of times model should train on data which is hyper parameter
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)

(1414, 13350)

In [29]:
custom_model.wv["farmers"]
# We get error becoz farmers word frequency is less than min_Count=5 which is defind during model declaration hyperparameter

array([ 1.54356589e-03, -2.54328479e-03,  2.72362237e-03,  3.57494876e-03,
        5.73055446e-03, -5.64070768e-04, -9.31898190e-04,  5.12229698e-03,
       -5.91211161e-03, -1.08119035e-04, -4.07798821e-03,  2.84220814e-03,
       -6.14241790e-03,  2.92070140e-03,  6.45068660e-03, -9.94301634e-04,
       -6.07953174e-03, -5.39848348e-03,  2.49375659e-03, -3.50942020e-03,
        3.98446107e-03, -1.13685464e-03,  5.53341396e-03, -4.65511293e-05,
       -4.33748495e-03, -4.39673383e-03,  2.17426481e-04, -2.99878279e-03,
        4.75083245e-03, -3.01303947e-03, -3.90113867e-03,  5.42541326e-04,
       -3.01793800e-03, -5.65142231e-03, -3.63776600e-03, -1.47306733e-03,
        9.08079732e-04,  2.46311305e-03,  4.83897794e-03,  4.54747723e-03,
        4.59698727e-03,  3.78290279e-04, -3.84249887e-03,  5.89483837e-03,
       -5.95723977e-04,  2.97065568e-03, -1.29086117e-03,  4.02966700e-03,
        3.44017334e-03, -4.86662192e-03, -1.99552602e-03,  8.26839823e-05,
        1.19009183e-03, -

In [30]:
#Get vector for tokens now
custom_model.wv["arjun"]

array([-4.7530793e-03,  1.9563313e-03,  1.4674700e-03,  4.3840329e-03,
       -3.5066863e-03, -3.1048905e-03, -4.3105846e-03,  3.1569619e-03,
       -3.3801608e-03,  5.9944610e-03, -2.4912003e-03, -6.5731178e-03,
       -3.4771713e-03,  5.1595522e-03, -3.6688505e-03, -3.0238049e-03,
       -5.1484928e-03,  4.0837266e-03,  2.6330331e-03,  1.9957109e-03,
       -2.4944462e-03,  3.7487745e-03, -3.7668850e-03, -9.9655311e-04,
       -4.2481124e-03, -1.3045031e-03, -1.7689752e-03,  5.9621008e-03,
        5.7703676e-04, -6.5113739e-03, -3.8862035e-03, -4.6409401e-03,
        1.9483486e-03,  6.2086945e-03, -4.0919934e-03,  5.2595548e-03,
        6.4550210e-03, -4.6234801e-03, -5.6133540e-03,  6.3618845e-03,
        6.4596646e-03, -2.9813389e-03, -4.4341655e-03,  5.1446352e-03,
        2.3550503e-03,  5.2113533e-03, -5.4699220e-03, -6.2120236e-03,
        9.7920350e-04, -6.6187023e-03, -3.5181476e-03, -2.2928757e-03,
        6.2967567e-03,  6.1023333e-03, -9.1263751e-04,  4.1154423e-03,
      

In [35]:
"farmers" in custom_model.wv


True

In [37]:
custom_model.wv.similarity("arjun","farmers")

0.08614112

In [127]:
custom_model.wv.similarity("farmers","farmers")

0.99999994

In [48]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)


(1437, 13350)

In [44]:
custom_model.wv.doesnt_match(["farmers","crop","arjun"])

'crop'

In [69]:
# Check pairwise similarities
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)

print(custom_model.wv.similarity("arjun", "farmers"))   # Should be Medium
print(custom_model.wv.similarity("arjun", "crop"))      # Should be LOWER
print(custom_model.wv.similarity("farmers", "crop"))    # Should be High


0.23160821
0.22658342
0.75137657


In [67]:
# Check pairwise similarities
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=30)

print(custom_model.wv.similarity("arjun", "farmers"))   # Should be Medium
print(custom_model.wv.similarity("arjun", "crop"))      # Should be LOWER
print(custom_model.wv.similarity("farmers", "crop"))    # Should be High


0.27360553
0.31313145
0.78178585


In [ ]:
# What's Happening — The Problem
# All scores dropped at 30 epochs! This is a sign of instability due to small data.
# 5 epochs  → model underfit  (not enough learning)
# 30 epochs → model confused  (too many updates on tiny data)
# With only 2 story files, the model has very few sentences to learn from.
#  More epochs means it keeps re-adjusting the same word vectors back and forth, causing them to drift rather than converge.

In [ ]:

custom_model.wv.most_similar("farmers")

[('system', 0.938004732131958),
 ('crop', 0.8382216691970825),
 ('many', 0.7917253971099854),
 ('weather', 0.7752374410629272),
 ('could', 0.7336434721946716),
 ('day', 0.7259054780006409),
 ('data', 0.7145825028419495),
 ('started', 0.7073631286621094),
 ('to', 0.6798452138900757),
 ('as', 0.6600257158279419)]

In [157]:
custom_model.train(story, total_examples=custom_model.corpus_count, epochs=10)
custom_model.wv.most_similar("farmers")

[('system', 0.9308730363845825),
 ('crop', 0.8322253227233887),
 ('many', 0.7902460694313049),
 ('weather', 0.7617910504341125),
 ('could', 0.7277421951293945),
 ('to', 0.7100537419319153),
 ('started', 0.7048071622848511),
 ('data', 0.6982532143592834),
 ('day', 0.6925271153450012),
 ('as', 0.6647911071777344)]

In [16]:
custom_model_For_Corp=gensim.models.Word2Vec(
   window=10,
   min_count=5,# min_count=5 is default value
   vector_size=100
   #sg=1
)
custom_model_For_Corp.build_vocab(story)
custom_model_For_Corp.train(story, total_examples=custom_model_For_Corp.corpus_count, epochs=5)
custom_model_For_Corp.wv["crop"]



array([ 8.2578333e-03, -4.8869278e-04, -9.4279191e-03,  4.9237832e-03,
       -6.1089844e-03,  6.5062079e-03,  5.5106985e-03, -4.6613384e-03,
        2.4726891e-03,  5.0724396e-03, -3.4598864e-03, -1.7520997e-03,
        9.2162052e-03,  9.2474241e-03, -9.3652345e-03,  7.4609993e-03,
        1.0141707e-02, -2.9079558e-03,  2.4657475e-03, -3.1295845e-03,
        8.8231163e-03, -2.7119089e-04,  5.9045106e-03,  9.1787158e-03,
        4.0279441e-03, -7.0692515e-03, -2.1286104e-03,  1.0496246e-03,
        2.0442605e-03,  3.0545921e-03,  9.6422425e-03,  4.2184833e-03,
        1.0096335e-02, -9.0951929e-03, -5.7630162e-03,  2.1290032e-03,
        3.7601073e-03, -1.0102398e-03, -7.0869797e-03, -3.2203023e-03,
       -8.4658507e-03,  9.2711486e-03,  3.5918220e-03, -7.8779068e-03,
        3.2391727e-03,  3.9138510e-03, -5.5925748e-03, -6.1096149e-03,
        1.1628594e-03,  9.0861619e-03, -9.5237400e-03, -1.3454746e-04,
       -6.9529917e-03, -8.9247257e-04,  3.0504402e-03, -4.9728919e-03,
      

In [17]:
custom_model_For_Corp=gensim.models.Word2Vec(
   window=10,
   min_count=5,# min_count=5 is default value
   vector_size=100
   #sg=1
)
custom_model_For_Corp.build_vocab(story)
custom_model_For_Corp.train(story, total_examples=custom_model_For_Corp.corpus_count, epochs=10)
custom_model_For_Corp.wv["crop"]



array([ 0.00790317, -0.00019716, -0.00952329,  0.00523198, -0.00627797,
        0.00604233,  0.00590074, -0.00373849,  0.0022121 ,  0.00420375,
       -0.00318547, -0.00228597,  0.00936368,  0.0096222 , -0.00926635,
        0.00723873,  0.0109868 , -0.00308276,  0.00248684, -0.00400942,
        0.00916003, -0.00018361,  0.00666675,  0.00906932,  0.0038404 ,
       -0.00694725, -0.00265943,  0.00123434,  0.00186652,  0.00337818,
        0.01039124,  0.00375282,  0.01056729, -0.01021261, -0.00584811,
        0.00263952,  0.00396977, -0.00097807, -0.00755751, -0.00321764,
       -0.00831974,  0.00898823,  0.00326311, -0.00778953,  0.00356464,
        0.00324454, -0.00558194, -0.00669644,  0.00160898,  0.00938918,
       -0.00922087, -0.00040603, -0.00723224, -0.00095013,  0.00301103,
       -0.00478602, -0.00213856,  0.00066902, -0.00654541,  0.00705035,
        0.00395177, -0.00906815, -0.00098581,  0.00375826, -0.00932842,
       -0.00580435, -0.00872956, -0.00497299,  0.00778894,  0.00

In [ ]:
# There is Reduce in vector values As epochs increase. in Above 2 Cells.W
# What's Happening — Learning Rate Decay
# Word2Vec uses a decreasing learning rate during training:
# python# Default values in gensim
# alpha     = 0.025   # starting learning rate
# min_alpha = 0.0001  # minimum learning rate As epochs increase,the learning rate gradually decreases:
# Epoch 1  → alpha = 0.025      (large updates)
# Epoch 5  → alpha = 0.012      (medium updates)
# Epoch 10 → alpha = 0.005      (small updates)
# Epoch 50 → alpha = 0.0001     (tiny updates, near frozen)
# So at epoch 10, the model is making smaller adjustments to vectors than at epoch 5 → values shift less → appear slightly reduced/stabilized.

In [ ]:
#Using skip-gram model for training now