In [1]:

from sklearn.feature_extraction.text import CountVectorizer

In [2]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]
     

In [3]:
bow = CountVectorizer()

In [4]:

bow_matrix =bow .fit_transform(documents)

In [5]:

bow_matrix

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [6]:

print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]
